image: christiankiely/meteord:test

services:
    - mongo

variables:
    METEOR_ALLOW_SUPERUSER: "true"

before_script:
    - meteor update
    - meteor npm install
    - meteor npm rebuild

test:
  script:
    - meteor npm it
