sudo: required

language: node_js
node_js:
  - node

before_install:
  - curl https://install.meteor.com | /bin/sh
  - export PATH="$HOME/.meteor:$PATH"
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

cache:
  directories:
    - node_modules

before_script:
  - meteor npm install

script:
  - npm t
  - meteor build $HOME
  - aws s3 cp --acl public-read $HOME/frontend.tar.gz s3://unee-t-media/frontend/commit/${COMMIT}.tar.gz
  - aws s3 cp --acl public-read $HOME/frontend.tar.gz s3://unee-t-media/frontend/${TRAVIS_BRANCH}.tar.gz

after_success:
    - ./deploy.sh

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}
